Add Circle CI integration
giantswarm/certificatetpr pull request #2
Opened 2017-03-24 11:10 UTC by rossf7

2017-03-24 11:12 UTC, xh3b4sd requested changes

2017-03-24 11:12 UTC, xh3b4sd commented on circle.yaml
> +        - cd $GS_WD && go build -a -v -tags netgo -ldflags "-w -X main.gitCommit=$(git rev-parse --short HEAD)"
Mr. @JosephSalisbury has an opinion here. I think we want to use architect here. See https://github.com/giantswarm/api/blob/master/circle.yml.

2017-03-24 11:15 UTC, rossf7 commented on circle.yaml
> +        - cd $GS_WD && go build -a -v -tags netgo -ldflags "-w -X main.gitCommit=$(git rev-parse --short HEAD)"
I based this off awstpr. I'll use api instead. Also the filename needs to be circle.yml

2017-03-24 11:27 UTC, rossf7 commented
Build succeeds now :)

2017-03-24 13:02 UTC, JosephSalisbury commented
Hmm, we look for a `main.go` to decide if we should run go build. I guess that doesn't make sense here.

2017-03-29 10:33 UTC, asymmetric commented
Closed by #5 I suppose? @JosephSalisbury does it make sense to use `architect` for this repo?

2017-03-29 20:15 UTC, JosephSalisbury commented
@asymmetric I'm assuming https://github.com/giantswarm/certificatetpr/pull/5 is a dupe of this PR. Addressed your comments there

2017-03-31 06:28 UTC, closed without merging